import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { operationsApi, type CashAccess, type CashMovement, type CashSession, type Currency, type ExchangeRate, type Patient, type Payment, type Quote, type TicketSettings } from '../../api/operations';
import { cashSummary, paymentPreview } from '../../domain/reception';

const money = (value: string | number, currency = 'MXN') => new Intl.NumberFormat('es-MX', { style: 'currency', currency }).format(Number(value));
type CashTab = 'operation' | 'movements' | 'open-close' | 'settings';

export function CashModule({ access, open, quotes, patients, movements, payments, activeRate, busy, onUnlock, onLock, onOpen, onPay, onMovement, onClose }: {
  access?: CashAccess; open?: CashSession; quotes: Quote[]; patients: Patient[]; movements: CashMovement[]; payments: Payment[]; activeRate?: ExchangeRate; busy: boolean;
  onUnlock: () => Promise<void>; onLock: () => Promise<void>; onOpen: (mxn: string, usd: string) => Promise<void>;
  onPay: (quoteId: string, amount: string, currency: Currency, method: 'cash' | 'card') => Promise<void>;
  onMovement: (kind: 'deposit' | 'withdrawal', currency: Currency, amount: string) => Promise<void>;
  onClose: (mxn: string, usd: string) => Promise<void>;
}) {
  const [tab, setTab] = useState<CashTab>('operation');
  const pending = quotes.filter((quote) => quote.status === 'issued');
  const [selectedId, setSelectedId] = useState(''); const [amount, setAmount] = useState('');
  const [currency, setCurrency] = useState<Currency>('MXN'); const [method, setMethod] = useState<'cash' | 'card'>('cash');
  const selected = pending.find((quote) => quote.id === selectedId); const patient = patients.find((item) => item.id === selected?.patient_id);
  const applied = payments.filter((item) => item.quote_id === selectedId).reduce((sum, item) => sum + Number(item.applied_mxn), 0);
  const debt = Math.max(0, Number(selected?.total_mxn ?? 0) - applied);
  const { changeMxn: change } = paymentPreview(Number(amount || 0), debt, currency, method, activeRate ? Number(activeRate.mxn_per_usd) : undefined);
  const summary = useMemo(() => cashSummary(movements, payments), [movements, payments]);

  if (!access?.unlocked) return <section className="cash-lock"><div className="cash-icon">🔒</div><h2>Caja protegida</h2><p>Apertura, efectivo, movimientos y cortes requieren una sesión temporal adicional.</p><button className="primary-action" disabled={busy} onClick={() => void onUnlock()}>Verificar acceso a Caja</button><small>No se almacena ninguna contraseña en el frontend.</small></section>;

  const nav = <nav className="cash-subtabs">{([['operation', 'Operación'], ['movements', 'Movimientos'], ['open-close', 'Apertura / Cierre'], ['settings', 'Configuración']] as const).map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}<button className="cash-lock-action" onClick={() => void onLock()}>Bloquear</button></nav>;

  if (!open) return <section className="cash-module">{nav}{access.mode === 'development_bypass' && <div className="inline-notice warning">Modo desarrollo: este desbloqueo no equivale a reautenticación productiva.</div>}{tab === 'open-close' ? <section className="cash-closed"><div className="cash-icon">▣</div><h2>Caja cerrada</h2><p>Captura los fondos físicos separados. Esta acción inicia la sesión operativa.</p><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void onOpen(String(data.get('mxn')), String(data.get('usd'))); }}><label>Fondo MXN<input name="mxn" defaultValue="0" type="number" min="0" step=".01" /></label><label>Fondo USD<input name="usd" defaultValue="0" type="number" min="0" step=".01" /></label><button className="primary-action" disabled={busy}>Abrir caja</button></form></section> : tab === 'settings' ? <TicketSettingsPanel /> : <div className="empty-detail cash-empty"><h2>Caja cerrada</h2><p>La apertura está disponible únicamente en Apertura / Cierre.</p></div>}</section>;

  function submitPayment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; void onPay(selected.id, amount, currency, method).then(() => { setAmount(''); setSelectedId(''); }); }
  return <section className="cash-module">{nav}{access.mode === 'development_bypass' && <div className="inline-notice warning">Modo desarrollo: este desbloqueo no equivale a reautenticación productiva.</div>}
    <header className="cash-status-bar"><span className="cash-open"><i /> Caja abierta</span><span>Apertura <b>{new Date(open.opened_at).toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' })}</b></span><span>Fondo <b>{money(open.opening_mxn)}</b> / <b>{money(open.opening_usd, 'USD')}</b></span><span>Efectivo <b className="positive">{money(open.physical_mxn)}</b> / <b className="positive">{money(open.physical_usd, 'USD')}</b></span></header>
    {tab === 'operation' && <><div className="cash-summary"><article><small>Ingresos en efectivo</small><b>{money(summary.ingresos)}</b></article><article><small>Egresos y cambio</small><b>{money(summary.egresos)}</b></article><article><small>Pagos con tarjeta</small><b>{money(summary.tarjetas)}</b></article><article><small>Pendientes</small><b>{pending.length}</b></article></div><div className="cash-workspace operation-only">
      <aside className="receivables"><div className="panel-kicker">POR COBRAR</div>{pending.map((quote) => { const p = patients.find((item) => item.id === quote.patient_id); return <button className={selectedId === quote.id ? 'selected' : ''} key={quote.id} onClick={() => { setSelectedId(quote.id); setAmount(''); }}><strong>{p ? `${p.last_name}, ${p.first_name}` : 'Cotización de mostrador'}</strong><span>{quote.lines.map((line) => line.name_snapshot).join(', ')}</span><small>Folio {quote.id.slice(0, 8).toUpperCase()}</small><b>{money(quote.total_mxn)}</b></button>; })}{!pending.length && <div className="empty-compact">No hay saldos pendientes.</div>}</aside>
      <article className="payment-panel"><div className="panel-kicker">NUEVO COBRO</div>{selected ? <form onSubmit={submitPayment}><div className="payment-identity"><strong>{patient ? `${patient.last_name}, ${patient.first_name}` : 'Mostrador'}</strong><span>{selected.lines.map((line) => line.name_snapshot).join(' · ')}</span><small>Folio {selected.id.slice(0, 8).toUpperCase()}</small></div><dl><div><dt>Total</dt><dd>{money(selected.total_mxn)}</dd></div><div><dt>Saldo</dt><dd>{money(debt)}</dd></div></dl><label>Importe recibido<input value={amount} onChange={(event) => setAmount(event.target.value)} required type="number" min=".01" step=".01" placeholder="0.00" /></label><div className="field-pair"><label>Moneda<select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option>MXN</option><option>USD</option></select></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value as 'cash' | 'card')}><option value="cash">Efectivo</option><option value="card">Tarjeta</option></select></label></div>{currency === 'USD' && <p className="conversion-note">Tasa vigente: 1 USD = {activeRate?.mxn_per_usd ?? 'sin configurar'} MXN</p>}<div className="change-preview"><span>Cambio en MXN</span><b>{money(change)}</b></div><button className="payment-submit" disabled={busy || !amount || (currency === 'USD' && !activeRate)}>Registrar cobro</button></form> : <div className="empty-detail">Selecciona una cotización pendiente.</div>}</article>
    </div></>}
    {tab === 'movements' && <section className="cash-ledger standalone-ledger"><div className="panel-kicker">MOVIMIENTOS DE LA SESIÓN</div><form className="movement-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void onMovement(String(data.get('kind')) as 'deposit' | 'withdrawal', String(data.get('currency')) as Currency, String(data.get('amount'))).then(() => form.reset()); }}><select name="kind"><option value="deposit">Entrada</option><option value="withdrawal">Egreso</option></select><select name="currency"><option>MXN</option><option>USD</option></select><input name="amount" type="number" min=".01" step=".01" placeholder="Monto" required /><button disabled={busy}>Registrar</button></form><div className="movement-list">{movements.map((item) => <div key={item.id}><span>{item.kind}<small>{new Date(item.created_at).toLocaleTimeString('es-MX')} · {item.currency}</small></span><b>{money(item.amount, item.currency)}</b></div>)}{!movements.length && <div className="empty-compact">Sin movimientos.</div>}</div></section>}
    {tab === 'open-close' && <footer className="cash-close"><div><div className="panel-kicker">CORTE DE CAJA</div><p>Esperado: <b>{money(open.physical_mxn)}</b> y <b>{money(open.physical_usd, 'USD')}</b></p></div><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void onClose(String(data.get('mxn')), String(data.get('usd'))); }}><label>Conteo final MXN<input name="mxn" type="number" min="0" step=".01" required /></label><label>Conteo final USD<input name="usd" type="number" min="0" step=".01" required /></label><button className="danger-action" disabled={busy}>Cerrar y generar corte</button></form></footer>}
    {tab === 'settings' && <TicketSettingsPanel />}
    <p className="integration-note">Ticket no fiscal. CFDI, terminal bancaria, impresora y cajón físico: no configurados.</p>
  </section>;
}

function TicketSettingsPanel() {
  const [value, setValue] = useState<TicketSettings>(); const [notice, setNotice] = useState('');
  useEffect(() => { operationsApi.ticketSettings().then(setValue).catch((e: Error) => setNotice(e.message)); }, []);
  if (!value) return <div className="dialog-state">{notice || 'Cargando configuración…'}</div>;
  const update = (key: keyof TicketSettings, next: string | boolean) => setValue({ ...value, [key]: next });
  const flags: Array<[keyof TicketSettings, string]> = [['show_logo', 'Mostrar logo'], ['show_folio', 'Mostrar folio'], ['show_patient', 'Mostrar paciente'], ['show_studies', 'Mostrar estudios'], ['show_line_prices', 'Precio por estudio'], ['show_subtotal', 'Subtotal'], ['show_total', 'Total'], ['show_currency', 'Moneda'], ['show_exchange_rate', 'Tipo de cambio'], ['show_payment_method', 'Forma de pago']];
  return <div className="ticket-settings"><form onSubmit={(event) => { event.preventDefault(); const { id, updated_at, updated_by, ...payload } = value; void operationsApi.saveTicketSettings(payload).then((saved) => { setValue(saved); setNotice('Configuración guardada.'); }); }}><div className="panel-kicker">CONFIGURACIÓN DE TICKET</div><label>Nombre comercial<input value={value.commercial_name} onChange={(e) => update('commercial_name', e.target.value)} required /></label><div className="field-pair"><label>Razón social<input value={value.legal_name ?? ''} onChange={(e) => update('legal_name', e.target.value)} /></label><label>RFC<input value={value.tax_id ?? ''} onChange={(e) => update('tax_id', e.target.value)} /></label></div><label>Dirección<input value={value.address ?? ''} onChange={(e) => update('address', e.target.value)} /></label><label>Teléfono<input value={value.phone ?? ''} onChange={(e) => update('phone', e.target.value)} /></label><label>Texto de encabezado<textarea value={value.header_text ?? ''} onChange={(e) => update('header_text', e.target.value)} /></label><label>Texto de pie<textarea value={value.footer_text ?? ''} onChange={(e) => update('footer_text', e.target.value)} /></label><label>Mensaje final<textarea value={value.final_message ?? ''} onChange={(e) => update('final_message', e.target.value)} /></label><div className="ticket-flags">{flags.map(([key, label]) => <label key={key}><input type="checkbox" checked={Boolean(value[key])} onChange={(e) => update(key, e.target.checked)} />{label}</label>)}</div><label>Ancho de papel<select value={value.paper_width} onChange={(e) => update('paper_width', e.target.value)}><option value="58mm">58 mm</option><option value="80mm">80 mm</option><option value="letter">Carta / impresora normal</option></select></label><button className="primary-action">Guardar configuración</button>{notice && <small>{notice}</small>}</form><TicketPreview value={value} /></div>;
}

function TicketPreview({ value }: { value: TicketSettings }) {
  return <aside className={`ticket-preview paper-${value.paper_width}`}><small>VISTA PREVIA · SIN VALIDEZ FISCAL</small>{value.show_logo && <div className="ticket-logo">APOLLO</div>}<h3>{value.commercial_name}</h3>{value.legal_name && <p>{value.legal_name}</p>}{value.tax_id && <p>RFC {value.tax_id}</p>}{value.header_text && <p>{value.header_text}</p>}<hr />{value.show_folio && <p>Folio Q-000042</p>}{value.show_patient && <p>Paciente: Persona de Prueba</p>}{value.show_studies && <p>US ABDOMEN {value.show_line_prices && '··· $1,200.00'}</p>}{value.show_subtotal && <p>Subtotal: $1,200.00</p>}{value.show_total && <h4>Total: $1,200.00 {value.show_currency && 'MXN'}</h4>}{value.show_exchange_rate && <p>1 USD = 18.50 MXN</p>}{value.show_payment_method && <p>Pago: efectivo</p>}{value.footer_text && <footer>{value.footer_text}</footer>}{value.final_message && <footer><b>{value.final_message}</b></footer>}<button onClick={() => window.print()}>Imprimir vista previa</button></aside>;
}
